server:
  port: 8081
spring:
  h2:
    console:
      enabled: true
      path: /product-db
      settings:
        trace: false
        web-allow-others: false
  datasource:
    url: jdbc:h2:mem:productdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect